{
  "info": {
    "author": "Delgan",
    "author_email": "delgan.py@gmail.com",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "**Note:** *This a fork of the original* ``better_exceptions`` *library.\nThis fork is intended to fix some edge cases I reported (see*\n`#47 <https://github.com/Qix-/better-exceptions/issues/47>`__), *but for\nthis it adds two dependencies to the project. The fixed errors are too\nsmall to justify the addition of dependency to the main library, hence\nthis fork that I publish for personal use.*\n\nbetter-exceptions |Travis|\n==========================\n\nPretty and more helpful exceptions in Python, automatically.\n\n.. image:: https://github.com/Delgan/better-exceptions/raw/master_fork/screenshot.png\n    :alt: Example screenshot of exceptions\n\nUsage\n-----\n\nInstall ``better_exceptions`` via pip:\n\n.. code:: console\n\n    $ pip install better_exceptions\n\nAnd set the ``BETTER_EXCEPTIONS`` environment variable to any value:\n\n.. code:: bash\n\n    export BETTER_EXCEPTIONS=1  # Linux / OSX\n    setx BETTER_EXCEPTIONS 1    # Windows\n\nThat's it!\n\nAdvanced Usage\n~~~~~~~~~~~~~~\n\nIf you want to allow the entirety of values to be outputted instead of\nbeing truncated to a certain amount of characters:\n\n.. code:: python\n\n    import better_exceptions\n    better_exceptions.MAX_LENGTH = None\n\nWhile using ``better_exceptions`` in production, do not forget to unset\nthe ``BETTER_EXCEPTIONS`` variable to avoid leaking sensitive data in\nyour logs.\n\nTroubleshooting\n---------------\n\nIf you do not see beautiful exceptions, first make sure that the\nenvironment variable does exist. You can try ``echo $BETTER_EXCEPTIONS``\n(Linux / OSX) or ``echo %BETTER_EXCEPTIONS%`` (Windows). On Linux and\nOSX, the ``export`` command does not add the variable permanently, you\nwill probably need to edit the ``~/.profile`` file to make it\npersistent. On Windows, you need to open a new terminal after the\n``setx`` command.\n\nYou should also note that ``better_exceptions`` does not work inside the\nPython interactive shell, unless the executed code comes from another\nfile.\n\nCheck that there is no conflict with another library, and that the\n``sys.excepthook`` function has been correctly replaced with the\n``better_exceptions``'s one. Sometimes other components can set up their\nown exception handlers, such as the ``python3-apport`` Ubuntu package\nthat you may need to uninstall.\n\nMake sure that you have not inadvertently deleted the\n``better_exceptions_hook.pth`` file that should be in the same place as\nthe ``better_exceptions`` folder where all of your Python packages are\ninstalled. Otherwise, try re-installing ``better_exceptions``.\n\nYou can also try to manually activate the hook by adding\n``import better_exceptions; better_exceptions.hook()`` at the beginning\nof your script.\n\nFinally, if you still can not get this module to work, `open a new\nissue <https://github.com/Qix-/better-exceptions/issues/new>`__ by\ndescribing your problem precisely and detailing your configuration\n(Python and ``better_exceptions`` versions, OS, code snippet,\ninterpeter, etc.) so that we can reproduce the bug you are experiencing.\n\nLicense\n=======\n\nCopyright \u00a9 2017, Josh Junon. Licensed under the `MIT\nlicense <LICENSE.txt>`__.\n\n.. |Travis| image:: https://img.shields.io/travis/Delgan/better-exceptions.svg?style=flat-square\n   :target: https://travis-ci.org/Delgan/better-exceptions",
    "docs_url": null,
    "download_url": "https://github.com/delgan/better-exceptions/archive/0.1.8.post0.tar.gz",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/delgan/better-exceptions",
    "keywords": "pretty,better,exceptions,exception,error,local,debug,debugging,locals",
    "license": "",
    "maintainer": "",
    "maintainer_email": "",
    "name": "better-exceptions-fork",
    "platform": "",
    "project_url": "https://pypi.org/project/better-exceptions-fork/",
    "release_url": "https://pypi.org/project/better-exceptions-fork/0.1.8.post0/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Pretty and helpful exceptions, automatically",
    "version": "0.1.8.post0"
  },
  "releases": {
    "0.1.8.post0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "7398cb3a4d04c1056c7dace24744f4ab",
          "sha256": "4305d9a4bbd4a4b5e61c8c52f0a349ca6229cde46b0c9ba9dbb514f3a29fa808"
        },
        "downloads": -1,
        "filename": "better_exceptions_fork-0.1.8.post0.tar.gz",
        "has_sig": false,
        "md5_digest": "7398cb3a4d04c1056c7dace24744f4ab",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 10643,
        "upload_time": "2017-10-08T17:14:45",
        "url": "https://files.pythonhosted.org/packages/eb/59/804bbe893101f3c6ed9b0624aa25b613e5610d5d265e2e26e5f8ada2b7cb/better_exceptions_fork-0.1.8.post0.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "7398cb3a4d04c1056c7dace24744f4ab",
        "sha256": "4305d9a4bbd4a4b5e61c8c52f0a349ca6229cde46b0c9ba9dbb514f3a29fa808"
      },
      "downloads": -1,
      "filename": "better_exceptions_fork-0.1.8.post0.tar.gz",
      "has_sig": false,
      "md5_digest": "7398cb3a4d04c1056c7dace24744f4ab",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 10643,
      "upload_time": "2017-10-08T17:14:45",
      "url": "https://files.pythonhosted.org/packages/eb/59/804bbe893101f3c6ed9b0624aa25b613e5610d5d265e2e26e5f8ada2b7cb/better_exceptions_fork-0.1.8.post0.tar.gz"
    }
  ]
}