{
  "info": {
    "author": "Hackathon",
    "author_email": "kimi.huang@brightcells.com",
    "bugtrack_url": null,
    "classifiers": [
      "License :: OSI Approved :: BSD License",
      "Programming Language :: Python",
      "Programming Language :: Python :: 2",
      "Programming Language :: Python :: 2.6",
      "Programming Language :: Python :: 2.7",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3.2",
      "Programming Language :: Python :: 3.3",
      "Programming Language :: Python :: 3.4",
      "Topic :: Software Development :: Libraries :: Python Modules"
    ],
    "description": "==============\npywe-exception\n==============\n\nWechat Exception Module for Python.\n\nInstallation\n============\n\n::\n\n    pip install pywe-exception\n\n\nUsage\n=====\n\n::\n\n    In [1]: from pywe_exception import WeChatException, WeChatPayException\n\n    In [2]: raise WeChatException({\"errcode\": 40125, \"errmsg\": \"invalid appsecret, view more at http://t.cn/RAEkdVq hint: [MVpSma0994e544]\"})\n    ---------------------------------------------------------------------------\n    WeChatException                           Traceback (most recent call last)\n    <ipython-input-2-793779f73857> in <module>()\n    ----> 1 raise WeChatException({\"errcode\": 40125, \"errmsg\": \"invalid appsecret, view more at http://t.cn/RAEkdVq hint: [MVpSma0994e544]\"})\n\n    WeChatException: {'errcode': 40125, 'errmsg': 'invalid appsecret, view more at http://t.cn/RAEkdVq hint: [MVpSma0994e544]'}\n\n\nMethod\n======\n\n::\n\n    class WeChatException(Exception):\n        \"\"\" WeChatException \"\"\"\n\n\n    class WeChatPayException(Exception):\n    \"\"\" WeChatPayException \"\"\"\n\n\n\n",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/sdkwe/pywe-exception",
    "keywords": "Wechat Weixin Exception",
    "license": "",
    "maintainer": "",
    "maintainer_email": "",
    "name": "pywe-exception",
    "platform": "",
    "project_url": "https://pypi.org/project/pywe-exception/",
    "release_url": "https://pypi.org/project/pywe-exception/1.0.2/",
    "requires_python": "",
    "summary": "Wechat Exception Module for Python.",
    "version": "1.0.2"
  },
  "releases": {
    "1.0.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "ef14695ce017247d01abbd6ed3439f27",
          "sha256": "263cae45e07c18bb8fe5fc06e3f852446c9116662ff1dd88d78555fe36313b5f"
        },
        "downloads": 13,
        "filename": "pywe_exception-1.0.2-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "ef14695ce017247d01abbd6ed3439f27",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 3309,
        "upload_time": "2017-02-24T11:39:54",
        "url": "https://files.pythonhosted.org/packages/10/e5/e39ebeb2122f47c0af0e45a5192945dae93046f7e582ef6e0feee9f060e5/pywe_exception-1.0.2-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "73fb6e82884d09bd8c475b20f8a0b0c4",
          "sha256": "cfe1fe4e19a6a15e53aafd11175254505507c84360b9eeb0bafcb2bf87ce2274"
        },
        "downloads": 10,
        "filename": "pywe-exception-1.0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "73fb6e82884d09bd8c475b20f8a0b0c4",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 1595,
        "upload_time": "2017-02-24T11:39:56",
        "url": "https://files.pythonhosted.org/packages/18/fd/d64ccf506fbcd292a8d6800ca76b81bd3fcf94056223ef7ee46cf6b933ac/pywe-exception-1.0.2.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "ef14695ce017247d01abbd6ed3439f27",
        "sha256": "263cae45e07c18bb8fe5fc06e3f852446c9116662ff1dd88d78555fe36313b5f"
      },
      "downloads": 13,
      "filename": "pywe_exception-1.0.2-py2.py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "ef14695ce017247d01abbd6ed3439f27",
      "packagetype": "bdist_wheel",
      "python_version": "py2.py3",
      "size": 3309,
      "upload_time": "2017-02-24T11:39:54",
      "url": "https://files.pythonhosted.org/packages/10/e5/e39ebeb2122f47c0af0e45a5192945dae93046f7e582ef6e0feee9f060e5/pywe_exception-1.0.2-py2.py3-none-any.whl"
    },
    {
      "comment_text": "",
      "digests": {
        "md5": "73fb6e82884d09bd8c475b20f8a0b0c4",
        "sha256": "cfe1fe4e19a6a15e53aafd11175254505507c84360b9eeb0bafcb2bf87ce2274"
      },
      "downloads": 10,
      "filename": "pywe-exception-1.0.2.tar.gz",
      "has_sig": false,
      "md5_digest": "73fb6e82884d09bd8c475b20f8a0b0c4",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 1595,
      "upload_time": "2017-02-24T11:39:56",
      "url": "https://files.pythonhosted.org/packages/18/fd/d64ccf506fbcd292a8d6800ca76b81bd3fcf94056223ef7ee46cf6b933ac/pywe-exception-1.0.2.tar.gz"
    }
  ]
}