{
  "info": {
    "author": "Huang Jiangbin",
    "author_email": "dobetter@zencore.cn",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3 :: Only",
      "Topic :: Software Development :: Libraries :: Python Modules"
    ],
    "description": "zenore-errors\n=============\n\nZencore error code collection.\n\n\n",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/zencore-dobetter/zencore-errors",
    "keywords": "zencore-errors",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "zencore-errors",
    "platform": "",
    "project_url": "https://pypi.org/project/zencore-errors/",
    "release_url": "https://pypi.org/project/zencore-errors/1.0.1/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Zencore error code collection",
    "version": "1.0.1"
  },
  "releases": {
    "1.0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "9f821c0a0de6b6642f3e6dca3017eb91",
          "sha256": "2583167d706ce1e5bbced231778974309169066f49686725a40360c168a80cdf"
        },
        "downloads": 0,
        "filename": "zencore-errors-1.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "9f821c0a0de6b6642f3e6dca3017eb91",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2128,
        "upload_time": "2017-07-12T01:19:35",
        "url": "https://files.pythonhosted.org/packages/39/60/121f30e9a318b3fd8fc248ddf08c97f543b77f732d857d8287fe19588235/zencore-errors-1.0.1.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "9f821c0a0de6b6642f3e6dca3017eb91",
        "sha256": "2583167d706ce1e5bbced231778974309169066f49686725a40360c168a80cdf"
      },
      "downloads": 0,
      "filename": "zencore-errors-1.0.1.tar.gz",
      "has_sig": false,
      "md5_digest": "9f821c0a0de6b6642f3e6dca3017eb91",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 2128,
      "upload_time": "2017-07-12T01:19:35",
      "url": "https://files.pythonhosted.org/packages/39/60/121f30e9a318b3fd8fc248ddf08c97f543b77f732d857d8287fe19588235/zencore-errors-1.0.1.tar.gz"
    }
  ]
}