{
  "info": {
    "author": "Huang Jiangbin",
    "author_email": "dobetter@zencore.cn",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3 :: Only",
      "Topic :: Software Development :: Libraries :: Python Modules"
    ],
    "description": "zenore-errors\n=============\n\n.. image:: https://travis-ci.org/zencore-dobetter/zencore-errors.svg?branch=master\n    :target: https://travis-ci.org/zencore-dobetter/zencore-errors\n\nZencore error code collection.\n\n\n",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/zencore-dobetter/zencore-errors",
    "keywords": "zencore-errors",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "zencore-errors",
    "platform": "",
    "project_url": "https://pypi.org/project/zencore-errors/",
    "release_url": "https://pypi.org/project/zencore-errors/1.0.4/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Zencore error code collection",
    "version": "1.0.4"
  },
  "releases": {
    "1.0.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "f22824df67da7137c4565e3595f27fd4",
          "sha256": "ee15e8d03bb626560b183c1a30e12013c0458f5d93da44d440fe4c305be14e1b"
        },
        "downloads": 0,
        "filename": "zencore-errors-1.0.4.tar.gz",
        "has_sig": false,
        "md5_digest": "f22824df67da7137c4565e3595f27fd4",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2253,
        "upload_time": "2017-08-10T14:04:23",
        "url": "https://files.pythonhosted.org/packages/d0/23/e7f1efe3ed3befcf9a144e83f76b668b5addfab9198d7a01dcbf2ca6711c/zencore-errors-1.0.4.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "f22824df67da7137c4565e3595f27fd4",
        "sha256": "ee15e8d03bb626560b183c1a30e12013c0458f5d93da44d440fe4c305be14e1b"
      },
      "downloads": 0,
      "filename": "zencore-errors-1.0.4.tar.gz",
      "has_sig": false,
      "md5_digest": "f22824df67da7137c4565e3595f27fd4",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 2253,
      "upload_time": "2017-08-10T14:04:23",
      "url": "https://files.pythonhosted.org/packages/d0/23/e7f1efe3ed3befcf9a144e83f76b668b5addfab9198d7a01dcbf2ca6711c/zencore-errors-1.0.4.tar.gz"
    }
  ]
}